### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nekromoff** [asimlqt/php-google-oauth#1]
this code:
if (isset($_GET['code'])) {
$client->authenticate();

should be this:
if (isset($_GET['code'])) {
$client->authenticate($_GET['code']);

otherwise fatal error is thrown.

**Comment by joelworsham** [comment]
+1

**Comment by ReekenX** [comment]
+1

Just spent hour because of that issue. Why it's taking so long to fix single line???

**Comment by SethArchambault** [comment]
+1

**Comment by asimlqt** [comment]
Sorry for the delay, this has been resolved now.

**Comment by joelworsham** [comment]
Thanks!
